version: '3.9'
services:
  trip-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'trip-backend:latest'
    container_name: trip-backend
    working_dir: /app
    command: [ "java", "-jar", "test.jar" ]
    restart: always
    ports:
      - '8080:8080'
